"""
OpticCrop / CropMind AI: Automated PDF Advisory Generator
Generates enterprise-grade agronomic advisory reports for farmers and agronomists.
"""

from fpdf import FPDF
import datetime
from typing import Optional, Dict, Any, List


class CropReportPDF(FPDF):
    def header(self):
        self.set_fill_color(11, 19, 38)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(255, 255, 255)
        self.set_y(4)
        self.cell(0, 10, "CROPMIND AI - PRECISION AGRICULTURE ADVISORY REPORT", 0, 1, "C")
        self.ln(6)
        self.set_text_color(30, 41, 59)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by CropMind AI Engine | Confidential Agronomic Intelligence", 0, 0, "C")


def sanitize_text(text: str) -> str:
    """Sanitizes text to standard latin-1 printable ASCII for PDF rendering."""
    if not text:
        return ""
    replacements = {
        "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--", "\u00b0": " deg ", "\u2265": ">=",
        "\u2264": "<=", "\u00b1": "+/-", "\u2022": "*", "\u2192": "->",
        "\u00b2": "2", "\u00b3": "3", "\u00d7": "x"
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


def generate_crop_report(
    crop_name: str,
    viability: float,
    n: float,
    p: float,
    k: float,
    temp: float,
    hum: float,
    ph: float,
    rain: float,
    summary: str,
    location_name: Optional[str] = "Selected Field Coordinates",
    positive_factors: Optional[List[str]] = None,
    negative_factors: Optional[List[str]] = None,
    fertilizer_advisory: Optional[str] = None
) -> bytes:
    """
    Generates a structured PDF advisory report and returns raw PDF bytes.
    """
    pdf = CropReportPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    
    # Header Information Box
    pdf.set_fill_color(241, 245, 249)
    pdf.rect(10, 24, 190, 24, "F")
    
    pdf.set_y(26)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(16, 185, 129)
    pdf.cell(120, 7, f"RECOMMENDED CROP: {sanitize_text(crop_name.upper())}", 0, 0)
    
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(70, 7, f"Viability Score: {viability*100:.1f}%", 0, 1, "R")
    
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(120, 6, f"Field Location: {sanitize_text(location_name)}", 0, 0)
    pdf.cell(70, 6, f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M UTC')}", 0, 1, "R")
    pdf.ln(6)
    
    # Soil & Meteorological Parameter Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, "1. FIELD EDAPHIC & METEOROLOGICAL PROFILE", 0, 1)
    
    # Table headers
    pdf.set_fill_color(226, 232, 240)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(95, 7, "  Edaphic Soil Parameters", 1, 0, "L", fill=True)
    pdf.cell(95, 7, "  Meteorological Climate Forecast", 1, 1, "L", fill=True)
    
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(95, 6, f"  Nitrogen (N): {n:.1f} mg/kg", 1, 0)
    pdf.cell(95, 6, f"  Ambient Temperature: {temp:.1f} C", 1, 1)
    
    pdf.cell(95, 6, f"  Phosphorus (P): {p:.1f} mg/kg", 1, 0)
    pdf.cell(95, 6, f"  Relative Humidity: {hum:.1f} %", 1, 1)
    
    pdf.cell(95, 6, f"  Potassium (K): {k:.1f} mg/kg", 1, 0)
    pdf.cell(95, 6, f"  Precipitation Sum: {rain:.1f} mm", 1, 1)
    
    pdf.cell(95, 6, f"  Soil pH Level: {ph:.2f}", 1, 0)
    pdf.cell(95, 6, f"  Derived N:P:K Ratio: {n/(p+1e-5):.1f} : 1.0 : {k/(p+1e-5):.1f}", 1, 1)
    pdf.ln(4)
    
    # Explainable AI Attribution Section
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, "2. EXPLAINABLE AI ATTRIBUTION (TreeSHAP)", 0, 1)
    
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(51, 65, 85)
    clean_summary = sanitize_text(summary)
    pdf.multi_cell(0, 6, clean_summary)
    pdf.ln(3)
    
    if positive_factors:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(16, 185, 129)
        pdf.cell(0, 6, "[+] Primary Positive Influences:", 0, 1)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(51, 65, 85)
        for factor in positive_factors:
            pdf.cell(0, 5, f"   - {sanitize_text(factor)}", 0, 1)
        pdf.ln(2)
        
    if negative_factors:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(225, 29, 72)
        pdf.cell(0, 6, "[-] Primary Limiting Factors & Constraints:", 0, 1)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(51, 65, 85)
        for factor in negative_factors:
            pdf.cell(0, 5, f"   - {sanitize_text(factor)}", 0, 1)
        pdf.ln(2)

    # Agronomic Action Plan
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 8, "3. AGRONOMIC ACTION PLAN & FERTIGATION GUIDANCE", 0, 1)
    
    adv_text = fertilizer_advisory or (
        f"Maintain balanced fertilization matching target uptake for {crop_name.capitalize()}. "
        f"Ensure optimal drainage during peak precipitation periods and monitor soil pH regularly."
    )
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(51, 65, 85)
    pdf.multi_cell(0, 6, sanitize_text(adv_text))
    
    # Return output bytes safely across fpdf / fpdf2 versions
    raw_output = pdf.output()
    if isinstance(raw_output, (bytes, bytearray)):
        return bytes(raw_output)
    elif isinstance(raw_output, str):
        return raw_output.encode("latin-1")
    return bytes(raw_output)
